# Generated by Django 3.1.4 on 2023-06-20 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackEspaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_esp', models.CharField(max_length=400, verbose_name='Feedback do Espaço')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.espaco')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_dis', models.CharField(max_length=400, verbose_name='Feedback da Disciplina')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.disciplina')),
            ],
        ),
    ]
