# Generated by Django 3.1.4 on 2023-05-08 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_disciplina',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.disciplina'),
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
