# Generated by Django 3.1.4 on 2023-05-08 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_espaco'),
        ('feedback', '0002_auto_20230508_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_Espaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_esp', models.CharField(max_length=400, verbose_name='Feedback do Espaço')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.espaco')),
            ],
        ),
    ]
