# Generated by Django 3.1.4 on 2023-05-11 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('codigo_pesquisa', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código da pesquisa')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título da Pesquisa')),
                ('data', models.DateTimeField(verbose_name='Data da Pesquisa')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('codigo_questao', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código da Questão')),
                ('texto', models.CharField(max_length=400, verbose_name='Texto da questão')),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisa_Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.IntegerField(verbose_name='Resposta-Pesquisa')),
                ('codigo_pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pesquisa.pesquisa', verbose_name='Código da Pesquisa')),
                ('codigo_questao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pesquisa.questao', verbose_name='Código da Questão')),
            ],
        ),
    ]
